CREATE TABLE asset_sequences (
  sequence_date CHAR(8) PRIMARY KEY,
  last_number INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ideas (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  asset_id VARCHAR(32) NOT NULL UNIQUE,
  title VARCHAR(120) NOT NULL,
  originator_email VARCHAR(255) NOT NULL,
  source VARCHAR(120),
  description TEXT,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assets (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  asset_id VARCHAR(32) NOT NULL UNIQUE,
  idea_id INTEGER NOT NULL,
  version VARCHAR(20) NOT NULL DEFAULT '0.1',
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idea_id) REFERENCES ideas(id)
);

CREATE TABLE contributors (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  display_name VARCHAR(120),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ledger (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  asset_id VARCHAR(32) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  event_payload TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_log (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  actor_email VARCHAR(255),
  action VARCHAR(80) NOT NULL,
  payload TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
